
"""
This program is designed to be used on simulation files generated by Zac Martinot to make the file 
names go from "2457755.11978.xx" to "zen.2457755.11978.xx.HH.SIM" so that the naming functions used 
by wedge_utils work.

The directory that these files are located in must be hardcoded.

Author:
Austin Fox Fortino <fortino_at_sas.upenn.edu>
"""
import glob, os, pprint

directory = glob.glob("path/to/files/*")
pprint.pprint(directory)

for file_loc in directory:
    file = '/'.join(file_loc.split('/')[:-1]) + '/' + 'zen.' + file_loc.split('/')[-1] + '.HH.SIM'
    print(file_loc)
    print(file)
    os.rename(file_loc, file)